branch-defaults:
  default:
    environment: project-one
environment-defaults:
  project-one:
    branch: null
    repository: null
global:
  application_name: Tattle-Sandbox
  default_ec2_keyname: null
  default_platform: arn:aws:elasticbeanstalk:ap-south-1::platform/Multi-container
    Docker running on 64bit Amazon Linux/2.18.0
  default_region: ap-south-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  sc: null
  workspace_type: Application
