name: deploy-staging

on: 
  push:
    branches: 
      - master
      - development

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Install EB-CLI
      run: pip install awsebcli --upgrade --user
      
    - name: deploy to ebs
      run: |
        mkdir ~/.aws
        echo '[profile eb-cli]' >> ~/.aws/config
        echo 'aws_access_key_id =' ${{ secrets.AWS_ACCESS_KEY_ID}} >> ~/.aws/config
        echo 'aws_secret_access_key =' ${{ secrets.AWS_SECRET_ACCESS_KEY }} >> ~/.aws/config
        ~/.local/bin/eb deploy project-one -l $GITHUB_SHA
